apiVersion: v1
kind: Template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mysql
    annotations:
      openshift.io/display-name: MySQL
  spec:
    tags:
    - name: '5.6'
      annotations:
        openshift.io/display-name: MySQL 5.6
        description: Provides a MySQL 5.6 database on CentOS 7. For more information
          about using this database image, including OpenShift considerations, see https://github.com/sclorg/mysql-container/tree/master/5.6.
        iconClass: icon-mysql-database
        tags: mysql
        version: '5.6'
      from:
        kind: DockerImage
        name: centos/mysql-56-centos7:latest
